name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++
    
    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make
        
    - name: Run tests
      run: |
        cd build
        ./lexer_unittest